### ISSUE TITLE
DCS 2.7 + A6E mod = CTD

### ISSUE THREAD

**Issue by clutchtomcat** [CorsairCat/DCS-A-6E-Intruder#3]
Since 2.7 the A-6E mod (and A-7 mod) show up as empty 3D models and cause CTDs. Are there any plans to update the 3D models to be compatible with 2.7? The Forrestal's flight deck sorely needs more Intruders and SLUFs.

**Comment by CorsairCat** [comment]
can you test with the latest version? This issue has been solved last month
