### ISSUE TITLE
After LODS update.... appeared a black box on HUD and VDI now show anyting more

### ISSUE THREAD

**Issue by paulocampoy** [CorsairCat/DCS-A-6E-Intruder#4]
Hi Team,

After file update A-6E.lods to run on versions higher than 2.7.5.... appeared a black box on HUD and VDI now show anything more.
I atached an image.

Best Regards

![A-6E_HUD_BLACKBOX_Image 2022-02-03 at 21 48 29](https://user-images.githubusercontent.com/38701792/152454190-78f00f18-0e7e-4df5-a5f0-af65138d8a56.png)

**Comment by dleffler** [comment]
This is not fixed? still appears this way in both last tagged release and main code

**Comment by themikewilson** [comment]
Did this get fixed? If so how? I have the same problem!

**Comment by paulocampoy** [comment]
No fixes was provide... this  project appears be freezed... te unique way
is turning the screen off on A-6 central console, pressing one of buttons
that will disable this screen, turning it of

Regards

---
Paulo Campoy


Em ter., 13 de fev. de 2024 04:07, themikewilson ***@***.***>
escreveu:

**Comment by themikewilson** [comment]
Thanks. I had the black square gone by removing the two files. I have a new problem now. I crashes the game after about a minute on the runway  so I can’t get to the fix you suggest.


Sent from Mail for Windows

**Comment by paulocampoy** [comment]
what files you removed?

---
Paulo Campoy


Em sex., 16 de fev. de 2024 21:49, themikewilson ***@***.***>
escreveu:

**Comment by themikewilson** [comment]
vdi.base and uhf.base from Cockpits/Scripts. That got rid of the black square but the VDI and UHF did not work of course.
After I heard from you I reloaded the original file but as I said it now crashes so I can’t test the console switches as you recommended. 

Sent from Mail for Windows

**Comment by paulocampoy** [comment]
Here is how to disable the black box...

https://www.youtube.com/watch?v=c9c2AfHIBM4&t=14s

---
Paulo Emidio de Mesquita Campoy

**Comment by CorsairCat** [comment]
Hello everyone, Yes, this mod has been paused long ago, idk if I can still find some time to fix these stuff.
